### ISSUE TITLE
Cleaning cruft for "Package Configs" gets stuck 

### ISSUE THREAD

**Issue by jqadev** [gerardpuig/ubuntu-cleaner#37]
Hi @gerardpuig,

I have installed Ubuntu Cleaner 1.1.2 on Ubuntu 20.04.
This application gets stuck on `Cleaning cruft for "Package Configs"` every time there is something to clean in this section.

![image](https://user-images.githubusercontent.com/20422423/79757791-d8551900-831c-11ea-9e74-b56a9b00fae2.png)

This issue doesn't exist in Ubuntu Cleaner 1.0.4 installed on Ubuntu 18.04.

**Comment by gerardpuig** [comment]
Hi @jqadev thanks for reporting this, I will take a look. Specially after final 20.04 is rolled out, currently it's still in beta.

**Comment by jqadev** [comment]
@gerardpuig, the issue still exists after release.

**Comment by JillyM** [comment]
Thanks for Ubuntu Cleaner, Gerard!
Same problem here, using Ubuntu release version 20.04 desktop/Unity 7.5. It may clean a single file in the Package Configs set, or none at all. I'll be happy to help test your fix.

**Comment by confusionists** [comment]
i have the same problem. after upgrading to 20.04 ubuntu cleaner hangs every time when cleaning the package configs. please fix.

**Comment by dipakvz** [comment]
I am using Pop_OS 20.04, I have also the same problem. please fix.

**Comment by mazvi** [comment]
I got same issue

**Comment by JillyM** [comment]
Gerard, we are worried about you. No reply in three weeks? We hope you are well, and can reply soon!
Best wishes from Jill and DIck.

**Comment by gerardpuig** [comment]
Hi all, I've just released version 1.1.3 which fixes this issue, cheers!

**Comment by jqadev** [comment]
I've just tested. It works like a charm.

**Comment by dipakvz** [comment]
> I've just received an update and tested it. It works like a charm. Thank you for your great work!



> Hi all, I've just released version 1.1.3 which fixes this issue, cheers!

Thank you for your great work....

**Comment by nikoskaraliolios** [comment]
hi, i still have the same problem. i'm using version 1.1.4-1 on Ubuntu 20.04.4 LTS on a Dell Inspiron
